Add home page
From-A2B/WebApp pull request #18
Opened 2024-06-23 13:07 UTC by BaptisteLegat

2024-07-10 13:49 UTC, Baptiste-Ferrand approved these changes

2024-07-12 14:54 UTC, Dercraker requested changes

2024-07-12 14:54 UTC, Dercraker commented on app/(landing-layout)/_component/ClientReviews/ClientReviews.tsx
> +];
Dont store fake data or data in component

2024-07-12 14:54 UTC, Dercraker commented on app/(landing-layout)/_component/ClientReviews/ClientReviews.tsx
> +};
One component by file

2024-07-12 14:54 UTC, Dercraker commented on app/(landing-layout)/_component/ClientReviews/ClientReviews.tsx
> +const secondRow = reviews.slice(reviews.length / 2);
write this inside of the component

2024-07-12 14:54 UTC, Dercraker commented on app/(landing-layout)/_component/ClientReviews/ClientReviews.tsx
Change name ClientReviews must be clientReviews

2024-07-12 14:54 UTC, Dercraker commented on app/(landing-layout)/_component/FeaturesSection.tsx
> +];
don't store data or fake data in component.

Either you create a seed with prisma, to faker the data in the db. Or you create a ts file in src/features/Home/features.ts which returns the data.

2024-07-12 14:54 UTC, Dercraker commented on app/(landing-layout)/_component/FeaturesSection.tsx
> +    </>
Here the artifact are useless

```suggestion
      <Container size="xl" mt="sm">
        <Stack w="100%" maw={400}>
          <Title order={1} c="teal" fw={900}>Features</Title>
        </Stack>
        <Stack w="100%" maw={600}>
          <Text size="lg" c="teal" my="sm">
            Here is the list of features included in our application and which you can discover.
          </Text>
        </Stack>
        <BentoGrid className="lg:grid-rows-3 mb-3">
          {features.map((feature) => (
            <BentoCard key={feature.name} {...feature} />
          ))}
        </BentoGrid>
        <Divider size={2} color="teal" mt="xl" />
      </Container>
```

2024-07-12 14:54 UTC, Dercraker commented on app/(landing-layout)/_component/FeaturesSection.tsx
The file name must be respect the camelCase convetion -> featuresSection.tsx

2024-07-12 14:54 UTC, Dercraker commented on app/(landing-layout)/_component/GlobeSection.tsx
> +    <>
useless artifact

2024-07-12 14:54 UTC, Dercraker commented on app/(landing-layout)/_component/GlobeSection.tsx
camelCase name for files

2024-07-12 14:54 UTC, Dercraker commented on app/(landing-layout)/_component/GlobeSection.tsx
> +    </>
useless artifact

2024-07-12 14:54 UTC, Dercraker commented on app/(landing-layout)/_component/GlobeSection.tsx
> +            <div className="relative flex h-full w-full max-w-[32rem] items-center justify-center overflow-hidden rounded-lg px-40 pb-40 pt-8 md:pb-60">
for flex flex-row you can use [Group](https://mantine.dev/core/group/) and for flex flex-col you can use [Stack](https://mantine.dev/core/stack/)

2024-07-12 14:54 UTC, Dercraker commented on app/(landing-layout)/_component/GlobeSection.tsx
> +            </Flex>
for the flex row you can use group

2024-07-12 14:54 UTC, Dercraker commented on app/(landing-layout)/_component/GlobeSection.tsx
camelCase for the file name

2024-07-12 14:54 UTC, Dercraker commented on app/(landing-layout)/_component/Hero/HeroHeader.tsx
> +import './HeroImageBackground.scss';
use mantine or tailwind before scss or css file

2024-07-12 14:54 UTC, Dercraker commented on app/(landing-layout)/_component/Hero/HeroHeader.tsx
> +    router.push('/trips');
use the constant LINKS to provide the href

2024-07-12 14:54 UTC, Dercraker commented on app/(landing-layout)/_component/Hero/HeroHeader.tsx
camelCase

2024-07-12 14:54 UTC, Dercraker commented on app/(landing-layout)/_component/Marquee/Marquee.tsx
remove the empty file

2024-07-12 14:54 UTC, Dercraker commented on app/(landing-layout)/_component/Hero/HeroImageBackground.scss
camelCase

2024-07-12 14:54 UTC, Dercraker commented on app/(landing-layout)/_component/StepSection.tsx
camelCase

2024-07-12 14:54 UTC, Dercraker commented on app/(landing-layout)/_component/TimelineAnimation/TimelineAnimation.tsx
camelCase

2024-07-12 14:54 UTC, Dercraker commented on app/(landing-layout)/_component/TestimonialsSection.tsx
camelCase

2024-07-12 14:54 UTC, Dercraker commented on playwright-report/index.html
gitignore ?

2024-07-12 14:54 UTC, Dercraker commented on src/components/video/Video.tsx
camelCase

2024-07-12 14:54 UTC, Dercraker commented on src/components/video/Video.tsx
> +export const Video: React.FC<VideoProps> = ({ source, children }) => {
why React.FC<VideoProps> ?

2024-07-12 14:54 UTC, Dercraker commented on src/hook/useScrollTrigger.ts
> +export default useScrollTrigger;
prefer export const .... than export default for hooks

2024-07-12 14:54 UTC, Dercraker commented on src/lib/utils.ts
> +}
we use arrow function like const funcName = (somes params) => {}

Cancel your edit

2024-07-12 19:44 UTC, BaptisteLegat commented on app/(landing-layout)/_component/ClientReviews/ClientReviews.tsx
> +];
Waiting [feat feedback](https://github.com/From-A2B/WebApp/pull/29) merge

2024-07-13 13:52 UTC, Dercraker commented on app/(landing-layout)/_component/ClientReviews/ClientReviews.tsx
camelCase

2024-07-13 13:52 UTC, Dercraker commented on app/(landing-layout)/_component/ClientReviews/reviewCard.tsx
camelCase

2024-07-13 13:52 UTC, Dercraker commented on app/(landing-layout)/_component/FeaturesSection.tsx
camelCase

2024-07-13 13:52 UTC, Dercraker commented on app/(landing-layout)/_component/GlobeSection.tsx
camelCase

2024-07-13 13:52 UTC, Dercraker commented on app/(landing-layout)/_component/Hero/HeroHeader.tsx
camelCase

2024-07-13 13:52 UTC, Dercraker commented on app/(landing-layout)/_component/StepSection.tsx
camelCase

2024-07-13 13:52 UTC, Dercraker commented on app/(landing-layout)/_component/TestimonialsSection.tsx
camelCase

2024-07-13 13:52 UTC, Dercraker commented on app/(landing-layout)/_component/TestimonialsSection.tsx
> +    <>
useless artifact

2024-07-13 13:52 UTC, Dercraker commented on app/(landing-layout)/_component/TimelineAnimation/TimelineAnimation.tsx
camelCase

2024-07-13 13:52 UTC, Dercraker commented on src/components/video/Video.tsx
camelCase

2024-07-13 15:18 UTC, Dercraker requested changes

2024-07-13 15:18 UTC, Dercraker commented on app/(base-layout)/feedback/_component/feedbackCarousel.tsx
> +    <>
useless artifact

2024-07-13 15:18 UTC, Dercraker commented on app/(base-layout)/support/_component/contact.form.tsx
> +import { TrashIcon } from '~/public/images/trash.icon';
```suggestion
import { TrashIcon } from '@/components/icons/trash.icon';
```

2024-07-13 15:18 UTC, Dercraker commented on app/(landing-layout)/_component/header/header.module.css
> +}
tu peut pas utiliser mantine ou tailwind pour sa ?

2024-07-13 15:18 UTC, Dercraker commented on src/components/contact/support/ContactSupportDialog.tsx
> +import { TrashIcon } from '~/public/images/trash.icon';
```suggestion
import { TrashIcon } from '@/components/icons/trash.icon';
```

2024-07-13 15:18 UTC, Dercraker commented on src/components/trip/createTripModal.tsx
> +import { TrashIcon } from '~/public/images/trashIcon';
```suggestion
import { CheckIcon } from '@/components/Icons/checkIcon';
import { TrashIcon } from '@/components/Icons/trashIcon';
```

2024-07-13 15:18 UTC, Dercraker commented on src/components/trip/createTripModal.tsx
> +import { CrossCircleIcon } from '../icons/crossCircle.icon';
```suggestion
import { CrossCircleIcon } from '@/components/Icons/crossCircle.icon';
```

2024-07-13 15:18 UTC, Dercraker commented on src/utils/NavigationLinks.tsx
> +import { WarnIcon } from '~/public/images/warn.icon';
```suggestion
import { UserIcon } from '@/components/icons/user.icon';
import { WarnIcon } from '@/components/icons/warn.icon';
```

2024-07-13 15:44 UTC, BaptisteLegat commented on app/(landing-layout)/_component/header/header.module.css
> +}
non

2024-07-16 09:58 UTC, Dercraker approved these changes

2024-07-16 09:58 UTC, Dercraker commented on app/(base-layout)/faq/page.tsx
> +'use client';
useless

2024-07-16 09:58 UTC, merged