add test jest and playwright
From-A2B/WebApp pull request #20
Opened 2024-07-02 08:22 UTC by BaptisteLegat

2024-07-10 13:50 UTC, Baptiste-Ferrand submitted a review, later dismissed

2024-07-12 14:58 UTC, Dercraker requested changes

2024-07-12 14:58 UTC, Dercraker commented on tests/E2E/landing/page.spec.ts
pull develop when https://github.com/From-A2B/WebApp/pull/18 is merged

2024-07-12 14:58 UTC, Dercraker commented on tests/jest/landing/page.test.jsx
pull develop when https://github.com/From-A2B/WebApp/pull/18 is merged

2024-07-12 14:58 UTC, Dercraker commented on app/(landing-layout)/page.tsx
pull develop when https://github.com/From-A2B/WebApp/pull/18 is merged

2024-10-28 19:51 UTC, closed without merging